apiVersion: v1
kind: Service
metadata:
  name: hk-deployment
spec:
  selector:
    app: hk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: 10.100.203.242
  type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: